models/Letter.php
<?php

namespace app\models;

class Letter extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%letter}}';
    }

    public static function selectAllUserLetters($user_id){
        return self::findAll(['user_id' => $user_id]);
    }
}

models/LetterForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\components\petrovich\Petrovich;
use kartik\mpdf\Pdf;
use yii\imagine\Image;
use yii\helpers\Html;

class LetterForm extends Model
{
    public $recipient_fam;
    public $recipient_name;
    public $recipient_patr;
    public $recipient_adress;
    public $recipient_flat;
    public $sender_fam;
    public $sender_name;
    public $sender_patr;
    public $sender_adress;
    public $sender_flat;
    public $template_id;
    public $pdf_link;

    public function rules()
    {
        return [
            [['recipient_fam', 'recipient_name', 'recipient_patr', 'recipient_adress', 'sender_fam', 'sender_name', 'sender_patr', 'sender_adress', 'template_id'], 'required', 'message' => "Поле обязательно для заполнения!"],
            ['template_id', 'templateValidation'],
        ];
    }

    public function templateValidation($attribute, $params)
    {
        if (!$this->hasErrors()) {
            if (!$this->templateExist($this->template_id)) {
                $this->addError($attribute, 'Указанного шаблона письма не существует!');
            }
        }
    }

    public function addLetter()
    {
        $recipient_fio = $this->fioConvert($this->recipient_fam, $this->recipient_name, $this->recipient_patr);
        $sender_fio = $this->fioConvert($this->sender_fam, $this->sender_name, $this->sender_patr, Petrovich::CASE_GENITIVE);
        $recipient_adress = json_decode($this->recipient_adress);
        $sender_adress = json_decode($this->sender_adress);

        $letter_data = [
            "recipient_fio" => $recipient_fio,
            "recipient_city" => $recipient_adress->region_with_type . ", " . $recipient_adress->city_with_type,
            "recipient_adress" => $recipient_adress->street_with_type . ", " . $recipient_adress->house_type . '. ' . $recipient_adress->house .( $this->recipient_flat ? ' - ' . $this->recipient_flat : ''),
            "recipient_postal_code" => $recipient_adress->postal_code,

            "sender_fio" => $sender_fio,
            "sender_city" => $sender_adress->region_with_type . ", " . $sender_adress->city_with_type,
            "sender_adress" => $sender_adress->street_with_type . ", " . $sender_adress->house_type . '. ' . $sender_adress->house .( $this->sender_flat ? ' - ' . $this->sender_flat : ''),
            "sender_postal_code" => $sender_adress->postal_code,
        ];

        $this->pdf_link = $this->createPdfLetter($this->template_id, $letter_data);

        $letter = new Letter();
        $letter->recipient_fio = $recipient_fio;
        $letter->recipient_adress = $this->recipient_adress;

        $letter->sender_fio = $sender_fio;
        $letter->sender_adress = $this->sender_adress;

        $letter->template_id = $this->template_id;
        $letter->pdf_link = $this->pdf_link;
        $letter->user_id = Yii::$app->user->id;
        $letter->save();

        return true;
    }

    public function fioConvert($fam, $name, $patr, $case = Petrovich::CASE_DATIVE){
        $petrovich = new Petrovich();
        $petrovich->setGender($petrovich->detectGender($patr));

        $fio = "";
        $fio = $petrovich->lastname($fam, $case).' ';
        $fio .= $petrovich->firstname($name, $case).' ';
        $fio .= $petrovich->middlename($patr, $case);



        return $fio;
    }

    private function templateExist($id)
    {
        return LetterTemplate::findOne(['id' => $id]) ? true : false;
    }


    private function createPdfLetter($template_id, $letter_data)
    {
        $letter_path = $this->generateLetter($template_id, $letter_data);
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;

        $pdf = new Pdf();
        $pdf = $pdf->api;
        $pdf->WriteHtml(Html::img($letter_path));
        unlink($letter_path);

        $pdf_dir_path = 'pdf_letters/';
        $pdf_name = $this->getRandomFileName(Yii::getAlias('@webroot/'.$pdf_dir_path),'pdf');
        $pdf->Output(Yii::getAlias('@webroot/'.$pdf_dir_path.$pdf_name), 'F');
        return $pdf_dir_path.$pdf_name;
    }

    private function generateLetter($template_id, $letter_data)
    {
        $temp_dir_path = Yii::getAlias('@webroot/outimages/');
        $img_path = $temp_dir_path . $this->getRandomFileName($temp_dir_path,'jpg');

        $positions = json_decode(LetterTemplate::selectTemplateJsonById($template_id), true);
        $image = Yii::getAlias('@webroot/'.LetterTemplate::selectTemplateLinkById($template_id));
        $fontFile = Yii::getAlias('@webroot/fonts/roboto/Roboto.woff');
        $fontOptions = [
            'size' => 30,    // Размер шрифта
            'color' => '000', // цвет шрифта
        ];
        $offset_x = 73;

        foreach ($positions as $position => $value) {
            if ($position == 'recipient_postal_code'){
                for ($i=0;$i<6;$i++){
                    $image = Image::text(
                        $image,                     // Картинка, на которой рисуем текст
                        $letter_data[$position][$i],    // Текст
                        $fontFile,                  // Путь к файлу шрифта
                        $value,                     // Отступ от левого края картинки
                        $fontOptions
                    )->save($img_path, ['quality' => 100]);
                    $value[0] += $offset_x;
                }
            }else{
                $image = Image::text(
                    $image,                     // Картинка, на которой рисуем текст
                    $letter_data[$position],    // Текст
                    $fontFile,                  // Путь к файлу шрифта
                    $value,                     // Отступ от левого края картинки
                    $fontOptions
                )->save($img_path, ['quality' => 100]);
            }
        }

        return $img_path;
    }

    private function getRandomFileName($path, $extension='')
    {
        $extension = $extension ? '.' . $extension : '';
        $path = $path ? $path . '/' : '';

        do {
            $name = md5(microtime() . rand(0, 9999));
            $file = $path . $name . $extension;
        } while (file_exists($file));

        return $name . $extension;
    }
}

controllers/LettersController.php
<?php

namespace app\controllers;

use app\models\Letter;
use Yii;
use yii\web\Controller;
use app\models\LetterForm;
use yii\imagine\Image;
use gietos\yii\Dadata\Client;

class LettersController extends Controller
{
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LetterForm();

        if ($model->load(Yii::$app->request->post()) && $model->addLetter()) {

            return $this->render('created', [
                'model' => $model,
            ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

//    public function actionEdit()
//    {
//        if (Yii::$app->user->isGuest) {
//            return $this->goHome();
//        }
//
//        $model = new LetterForm();
//
//        if ($model->load(Yii::$app->request->post()) && $model->addLetter()) {
//
//            return $this->render('created', [
//                'model' => $model,
//            ]);
//        }
//
//        return $this->render('create', [
//            'model' => $model,
//        ]);
//    }

    public function actionCabinet()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        return $this->render('cabinet', [
            'model' => $model,
        ]);
    }

    public function actionDownload($file) {
        if (file_exists($file)) {
            return \Yii::$app->response->sendFile($file);
        }
        throw new \Exception('File not found');
    }

//    public function actionDownloadById($id) {
//        $file = Letter::findOne(['id' => $id])->pdf_link;
//        if (file_exists($file)) {
//            return \Yii::$app->response->sendFile($file);
//        }
//        throw new \Exception('File not found');
//    }

    public function actionView($file)
    {
        if (file_exists($file)) {
            return Yii::$app->getResponse()->redirect($file);
//            return \Yii::$app->response->sendFile($file, ['inline'=>true]);
        }
        throw new \Exception('File not found');
    }

    public function actionDelete($id){
        Letter::deleteAll(['id' => $id]);

        return $this->render('cabinet', [
            'model' => $model,
        ]);
    }

    public function actionGetThumbnail()
    {
        $template_id = Yii::$app->request->post('template_id');
        $size = Yii::$app->request->post('size');

        $default_size = 500;
        $root_path = '@webroot/';
        $image_name = 'letter'.$template_id;
        $image_dir = Yii::getAlias($root_path.'letters/opacity/');
        $image_extension = '.png';
        $image = $image_dir.$image_name.$image_extension;


        $size_x = $size ? $size : $default_size;
        $size_y = $size_x*1.414;
        $thumb_path = Yii::getAlias('letters/opacity/thumbnails/'.$image_name.'-'.$size_x.'x'.round($size_y).$image_extension);
        $full_thumb_path = Yii::getAlias($root_path.$thumb_path);

        if (!file_exists($full_thumb_path)) {
            Image::thumbnail($image, $size_x, $size_y)
                ->save($full_thumb_path, ['quality' => 100]);
        }

        return $thumb_path;
    }
}

views/letters/_list_view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$recipient_adress = json_decode($model->sender_adress);
$sender_adress = json_decode($model->recipient_adress);

$sender_adress = $sender_adress->region_with_type . ", " . $sender_adress->city_with_type . ", " . $sender_adress->street_with_type . ", " . $sender_adress->house_type . '. ' . $sender_adress->house;
$recipient_adress = $recipient_adress->region_with_type . ", " . $recipient_adress->city_with_type . ", " . $recipient_adress->street_with_type . ", " . $recipient_adress->house_type . '. ' . $recipient_adress->house;
?></pre>
<div class="col-12 py-3 secondary my-3 letter-info rounded">
    <div class="row">
        <div class="col-6 text-success pr-0 text-right">ФИО получателя:</div><div class="col-6"><?=$model->recipient_fio;?></div>
    </div>
    <div class="row">
        <div class="col-6 text-success pr-0 text-right">Адрес получателя:</div><div class="col-6"><?=$recipient_adress;?></div>
    </div>
    <div class="row">
        <div class="col-6 text-success pr-0 text-right">ФИО отправителя:</div><div class="col-6"><?=$model->sender_fio;?></div>
    </div>
    <div class="row">
        <div class="col-6 text-success pr-0 text-right">Адрес отправителя:</div><div class="col-6"><?=$sender_adress;?></div>
    </div>
    <div class="row">
        <div class="col-6 text-success pr-0 text-right">Дата создания:</div><div class="col-6"><?=$model->creation_date;?></div>
    </div>

    <div class="row mt-3 justify-content-center">
        <div class="col-12 col-lg-8 offset-2">
            <?=Html::a("Скачать", Url::toRoute(['letters/download', 'file' => $model->pdf_link]), ['class' => 'col-5 col-lg-2 btn btn-success'])?>
            <?=Html::a("Открыть", Url::toRoute(['letters/view', 'file' => $model->pdf_link]), ['class' => 'col-5 col-lg-2 btn btn-primary'])?>
            <?=Html::a("Редактировать", Url::toRoute(['letters/create', 'id' => $model->id]), ['class' => 'col-lg-3 col-5 mt-2 mt-lg-0 btn btn-secondary'])?>
            <?=Html::a("Удалить", Url::toRoute(['letters/delete', 'id' => $model->id]), ['class' => 'delete col-5 col-lg-2 mt-2 mt-lg-0 btn btn-danger'])?>
        </div>
    </div>
</div>

<?php
$js = <<<JS
    $('.delete').on('click', function(){
      if(!confirm('Вы уверены, что хотите удалить конверт?')){
          return false;
      }  
    })
JS;
$this->registerJs($js);
?>

views/letters/cabinet.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\imagine\Image;
use \app\models\Letter;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use yii\widgets\ListView;

$this->title = 'Личный кабинет';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1 class="text-primary"><?= Html::encode($this->title) ?></h1>
    <h4>Добро пожаловать, <?= Html::encode(Yii::$app->user->identity->fio) ?>!</h4>
    <div class="row">
        <div class="col-6 col-lg-3">
            <?=Html::a('Создать новый конверт', Url::toRoute('letters/create'), ['class' => 'col-12 btn btn-success'])?>
        </div>
        <div class="col-6 col-lg-3 offset-lg-6">
            <?=
            Html::beginForm(['/site/logout'], 'post')
            .Html::submitButton('Выйти',['class' => 'col-12 btn btn-success'])
            .Html::endForm();
            ?>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <?php
        $dataProvider = new ActiveDataProvider([
            'query' => Letter::find()->where(['user_id' => Yii::$app->user->id]),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);

//        echo GridView::widget([
//            'dataProvider' => $dataProvider,
//            'columns' => [
//                ['class' => 'yii\grid\SerialColumn'],
//                'recipient_fio:ntext:ФИО получателя',
//                'recipient_adress:ntext:Адрес получателя',
//                'sender_fio:ntext:ФИО отправителя',
//                'sender_adress:ntext:Адрес отправителя',
//                'creation_date:date:Дата создания',
//                [
//                    'class' => 'yii\grid\ActionColumn',
//                    'header'=>'Письма',
//                    'template' => '{download-by-id}',
//                    'buttons' => [
//                        'download-by-id' => function($data){
//                            return Html::a('Скачать', $data,['class' => 'btn btn-primary']);
//                        },
//                    ],
//                ],
//                ['class' => 'yii\grid\ActionColumn',
//                    'header'=>'Действия',
//                    'template' => '{view}', //'{view} {edit} {delete}',
//                    'buttons' => [
//                        'view' => function($data){
//                            return Html::a('Просмотр',$data,['class' => 'btn btn-primary']);
//                        },
//                    ],
//                ],
//            ],
//
//            'options' => ['class' => 'table-responsive'],
//            'tableOptions' => ['class' => 'table table-condensed'],
//        ]);
            echo ListView::widget([
                'dataProvider' => $dataProvider,
                'class' => 'letters-view',
                'itemView' => '_list_view',
                'pager' => [
                    'firstPageLabel' => 'В начало',
                    'lastPageLabel' => 'В конец',
                    'nextPageLabel' => '>',
                    'prevPageLabel' => '<',
                    'maxButtonCount' => 3,
                ],
            ]);
        ?>
        </div>
    </div>
</div>

views/letters/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use \app\models\LetterTemplate;
use yii\helpers\ArrayHelper;

$this->title = 'Новый конверт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="letters-create">
    <h1 class="text-primary"><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin([
        'id' => 'letter-form',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n<div class=\"pl-0 col-12 text-danger\">{error}</div>",
            'labelOptions' => ['class' => 'control-label'],
        ],
    ]); ?>
    <?php
    $templates = LetterTemplate::find()->all();
    $items = ArrayHelper::map($templates, 'id', 'link');
    ?>

    <div class="row">
        <div class="col-12">
        <span class="d-none v-0">
            <?= $form->field($model, 'template_id')->dropDownList($items,['id' => 'temp_id', 'class' => 'd-none'])->label('')?>
            <?= $form->field($model, 'recipient_adress')->textInput(['class' => 'd-none'])->label('')?>
            <?= $form->field($model, 'sender_adress')->textInput(['class' => 'd-none'])->label('')?>
            <?= $form->field($model, 'recipient_flat')->textInput(['class' => 'd-none'])->label('')?>
            <?= $form->field($model, 'sender_flat')->textInput(['class' => 'd-none'])->label('')?>
        </span>
        <div class="row">
            <div class="col-md-4">
                <h4>Получатель письма <p class="small">(в именительном падеже)</p></h4>
                <?= $form->field($model, 'recipient_fam')->textInput(['placeholder' => 'Фамилия'])->label('Фамилия') ?>
                <?= $form->field($model, 'recipient_name')->textInput(['placeholder' => 'Имя'])->label('Имя')?>
                <?= $form->field($model, 'recipient_patr')->textInput(['placeholder' => 'Отчество'])->label('Отчество')?>


                <label>Адрес получателя</label>
                <div class="row mx-1">
                    <?=Html::textInput("","",['id' => 'recipient_region', 'required' => true, 'placeholder' => 'Область', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'recipient_city', 'required' => true, 'placeholder' => 'Город', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'recipient_street', 'required' => true, 'placeholder' => 'Улица', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'recipient_house', 'required' => true, 'placeholder' => 'Дом', 'class' => 'mb-2 col-5 form-control'])?>
                    <?=Html::textInput("","",['id' => 'recipient_flat', 'placeholder' => 'Квартира', 'class' => 'col-5 ml-auto mr-0 form-control'])?>
                </div>
            </div>
            <div class="col-md-4">
                <h4>Отправитель письма<p class="small">(в именительном падеже)</p></h4>
                <?= $form->field($model, 'sender_fam')->textInput(['placeholder' => 'Фамилия'])->label('Фамилия')?>
                <?= $form->field($model, 'sender_name')->textInput(['placeholder' => 'Имя'])->label('Имя')?>
                <?= $form->field($model, 'sender_patr')->textInput(['placeholder' => 'Отчество'])->label('Отчество')?>

                <label>Адрес отправителя</label>
                <div class="row mx-1">
                    <?=Html::textInput("","",['id' => 'sender_region', 'required' => true, 'placeholder' => 'Область', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'sender_city', 'required' => true, 'placeholder' => 'Город', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'sender_street', 'required' => true, 'placeholder' => 'Улица', 'class' => 'mb-2 form-control'])?>
                    <?=Html::textInput("","",['id' => 'sender_house', 'required' => true, 'placeholder' => 'Дом', 'class' => 'mb-2 col-5 form-control'])?>
                    <?=Html::textInput("","",['id' => 'sender_flat', 'placeholder' => 'Квартира', 'class' => 'col-5 ml-auto mr-0 form-control'])?>
                </div>
            </div>
            <div class="col-md-4">
                <h4>Выберите конверт</h4>
                <div class="letter-info">
                    <?=Html::tag('a', 'Предыдущий',['id' => 'prev_letter', 'class' => 'col-4 col-sm-6 col-md-4 btn btn-secondary']);?>
                    <?=Html::tag('a', 'Следующий',['id' => 'next_letter', 'class' => 'col-4 col-sm-6 col-md-4 float-right btn btn-secondary']);?>
                    <?=Html::img('',['id' => 'letter_template', 'class' => 'col-12'])?>
                </div>
            </div>
        </div>
        <div class="form-group mt-3">
            <?= Html::a('Назад', Url::toRoute(['letters/cabinet']),['class' => 'btn btn-primary btn-lg']) ?>
            <?= Html::submitButton('Создать конверт', ['class' => 'float-right btn btn-success btn-lg', 'name' => 'letter-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php
$url = Url::toRoute(["letters/get-thumbnail"]);
$size = 400;
$js=<<<JS
    $(function(){
        get_letter_template(1,$size);
        
        $("#next_letter").on("click", function(e) {
            get_next_template($size);      
        });
    
        $("#prev_letter").on("click", function(e) {
            get_prev_template($size);      
        });
        
        $('#letter-form').submit(function(e){
            if (!$('#letterform-sender_adress').val && !$('#letterform-sender_adress').val){
                alert('Вы не указали адрес!');
                e.preventDefault();
            };
        });
    });

    function get_next_template(size){
        id = $('#temp_id').val();
        if(id == $('#temp_id option').length){
            return;
        }
        get_letter_template(++id,size);
        $('#temp_id option[value=' + id + ']').prop('selected', true);
    }
    
    function get_prev_template(size){
        id = $('#temp_id').val();
        if(id == 1){
            return;
        }
        get_letter_template(--id,size);
        $('#temp_id option[value=' + id + ']').prop('selected', true);
    }

    function get_letter_template(id, size){
        
        $.ajax({
                url: "$url",
                type : "POST",
                data : {template_id:id,size:size},
                success : function(res){
                   $('#letter_template').attr('src', res);
                },
            error : function(){
                alert("Ошибка при отправке данных: перезагрузите страницу!");
            }
            })
            return false;  
    }    
JS;
$this->registerJs($js);
?>

views/letters/created.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="site-contact">
    <h1 class="text-primary">Ваше письмо успешно создано!</h1>
        <div class="row">
            <div class="col">
                <?=Html::a('Скачать письмо',Url::toRoute(['/letters/download','file' => $model->pdf_link]),['class' => 'btn btn-success']);?>
            </div>
            <div class="col">
                <?=Html::a('Открыть в браузере', $model->pdf_link,['class' => 'btn btn-primary']);?>
            </div>
            <div class="col">
                <?=Html::a('Личный кабинет', Url::toRoute('/letters/cabinet'),['class' => 'btn btn-info']);?>
            </div>
        </div>
</div>

views/letters/edit.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use \app\models\LetterTemplate;
use yii\helpers\ArrayHelper;

$this->title = 'Новый конверт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1 class="text-primary"><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin([
        'id' => 'letter-form',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n<div class=\"pl-0 col-12 text-danger\">{error}</div>",
            'labelOptions' => ['class' => 'control-label'],
        ],
    ]); ?>
    <?php
    $templates = LetterTemplate::find()->all();
    $items = ArrayHelper::map($templates, 'id', 'link');
    ?>

    <div class="row">
        <div class="col-12">
        <?= $form->field($model, 'template_id')->dropDownList($items,['id' => 'temp_id', 'class' => 'd-none'])->label('')?>

        <div class="row">
            <div class="col-md-4">
                <h4>Получатель письма <p class="small">(в именительном падеже)</p></h4>
                <?= $form->field($model, 'recipient_fam')->label('Фамилия') ?>
                <?= $form->field($model, 'recipient_name')->label('Имя')?>
                <?= $form->field($model, 'recipient_patr')->label('Отчество')?>

                <?= $form->field($model, 'recipient_adress')->label('Адрес получателя')?>
            </div>
            <div class="col-md-4">
                <h4>Отправитель письма<p class="small">(в именительном падеже)</p></h4>
                <?= $form->field($model, 'sender_fam')->label('Фамилия')?>
                <?= $form->field($model, 'sender_name')->label('Имя')?>
                <?= $form->field($model, 'sender_patr')->label('Отчество')?>
                <?= $form->field($model, 'sender_adress')->label('Адрес отправителя')?>
            </div>
            <div class="col-md-4">
                <h4>Выберите конверт</h4>
                <?=Html::tag('a', 'Предыдущий',['id' => 'prev_letter', 'class' => 'btn btn-primary']);?>
                <?=Html::tag('a', 'Следующий',['id' => 'next_letter', 'class' => 'float-right btn btn-primary']);?>
                <?=Html::img('',['id' => 'letter_template', 'class' => 'col-12'])?>
            </div>
        </div>
        <div class="form-group">
            <?= Html::a('Назад', Url::toRoute(['letters/cabinet']),['class' => 'btn btn-primary btn-lg']) ?>
            <?= Html::submitButton('Создать конверт', ['class' => 'btn btn-success btn-lg', 'name' => 'letter-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php
$url = Url::toRoute(["letters/get-thumbnail"]);
$size = 400;
$js=<<<JS
    $(function(){
        get_letter_template(1,$size);
        
        $("#next_letter").on("click", function(e) {
            get_next_template($size);      
        });
    
        $("#prev_letter").on("click", function(e) {
            get_prev_template($size);      
        });
    });

    function get_next_template(size){
        id = $('#temp_id').val();
        if(id == $('#temp_id option').length){
            return;
        }
        get_letter_template(++id,size);
        $('#temp_id option[value=' + id + ']').prop('selected', true);
    }
    
    function get_prev_template(size){
        id = $('#temp_id').val();
        if(id == 1){
            return;
        }
        get_letter_template(--id,size);
        $('#temp_id option[value=' + id + ']').prop('selected', true);
    }

    function get_letter_template(id, size){
        
        $.ajax({
                url: "$url",
                type : "POST",
                data : {template_id:id,size:size},
                success : function(res){
                   $('#letter_template').attr('src', res);
                },
            error : function(){
                alert("Ошибка при отправке данных: перезагрузите страницу!");
            }
            })
            return false;  
    }
JS;
$this->registerJs($js);
?>